minr fixes

diff --git a/bin/vt/vm-create b/bin/vt/vm-create
--- a/bin/vt/vm-create
+++ b/bin/vt/vm-create
@@ -37,8 +37,8 @@ configure_alpine() {
     USERNAME=${USERNAME:=$DISTRO}
     RELEASE=${RELEASE:=3.22}
 
-    IMG_URL="https://dl-cdn.alpinelinux.org/alpine/v${RELEASE}/releases/x86_64/alpine-virt-3.22-x86_64.qcow2"
-    BASE_IMG_NAME="alpine-virt-3.22-x86_64.qcow2"
+    IMG_URL="https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/generic_alpine-${RELEASE}.0-x86_64-uefi-cloudinit-r0.qcow2"
+    BASE_IMG_NAME="generic_alpine-${RELEASE}.0-x86_64-uefi-cloudinit-r0.qcow2"
     USER_GROUPS=("wheel")
     # INSTALL_CMD="sudo apk add qemu libvirt qemu-img wget genisoimage"
 
@@ -46,9 +46,9 @@ configure_alpine() {
     osinfo_list=$(virt-install --osinfo list 2>/dev/null)
 
     if ! echo "$osinfo_list" | grep -q "alpinelinux${RELEASE}"; then
-        warn "OS variant 'fedora${RELEASE}' not found in virt-install osinfo list, using 'fedora41'"
-        slog "Available fedora variants:"
-        echo "$osinfo_list" | grep -i fedora | head -5 || true
+        warn "OS variant 'alpine${RELEASE}' not found in virt-install osinfo list, using 'alpinelinux3.21'"
+        slog "Available alpine variants:"
+        echo "$osinfo_list" | grep -i alpine | head -5 || true
         OS_VARIANT="alpinelinux3.21"
     fi
 }
