minor fixes to vme scripts

diff --git a/bin/vt/vme-tmux b/bin/vt/vme-tmux
--- a/bin/vt/vme-tmux
+++ b/bin/vt/vme-tmux
@@ -11,12 +11,12 @@ vme_exists() {
   virsh dominfo "$1" &>/dev/null
 }
 
-VM_DISTRO_LIST=("ubuntu" "fedora" "arch" "debian" "tumbleweed")
+VM_DISTRO_LIST=("ubuntu" "fedora" "arch" "debian" "tw")
 
 SESSION_NAME="VME_TMUX"
 
 usage() {
-    cat <<EOF
+  cat <<EOF
 Usage: $(basename "$0") [OPTION]
 
 Manage a tmux session with SSH connections to libvirt VMs.
@@ -38,59 +38,79 @@ EOF
 }
 
 check_prerequisites() {
-    vm_check_prerequisites
-    check_tmux
+  vm_check_prerequisites
+  check_tmux
 }
 
+create_commands() {
+  if [ "$#" -lt 3 ]; then
+    echo "Usage: create_commands <output_array_name> <prefix> <distro1> ..." >&2
+    return 1
+  fi
+
+  local -n cmds
+  cmds="$1"
+  local cmd_prefix="$2"
+  shift 2
+
+  local -a distro_list=("$@")
+
+  cmds=()
+  local username="$USER"
+  for distro in "${distro_list[@]}"; do
+    cmds+=("${cmd_prefix} ssh ${distro}-${cmd_prefix} ${username}")
+  done
+}
+
+# @TODO: This is temporary. Only until all username/password are in sync.
 create_session() {
+  tmux_session "$SESSION_NAME" "$1"
 
-    tmux_session "$SESSION_NAME" "$1"
+  slog "Creating tmux session '$SESSION_NAME' with SSH connections to libvirt VMs..."
 
-    slog "Creating tmux session '$SESSION_NAME' with SSH connections to libvirt VMs..."
+  local ssh_cmds=()
+  create_commands ssh_cmds "vme" "${VM_DISTRO_LIST[@]}"
 
-    local ssh_cmds=()
-    create_commands ssh_cmds "vme" "${VM_DISTRO_LIST[@]}"
+  start_sessions "vme" "${VM_DISTRO_LIST[@]}"
 
-    start_sessions "vme" "${VM_DISTRO_LIST[@]}"
+  if ! tmux_grid "$SESSION_NAME" "${ssh_cmds[@]}"; then
+    fail "Failed to create tmux session '$SESSION_NAME' with SSH connections to VMs."
+    return 1
+  fi
 
-    if ! tmux_grid "$SESSION_NAME" "${ssh_cmds[@]}"; then
-        fail "Failed to create tmux session '$SESSION_NAME' with SSH connections to VMs."
-        return 1
-    fi
-
-    if ! tmux attach-session -t "$SESSION_NAME"; then
-        fail "Failed to attach to tmux session '$SESSION_NAME'."
-        return 1
-    fi
+  if ! tmux attach-session -t "$SESSION_NAME"; then
+    fail "Failed to attach to tmux session '$SESSION_NAME'."
+    return 1
+  fi
 }
 
 main() {
-    local command="${1:-}"
+  local command="${1:-}"
 
-    check_prerequisites
+  check_prerequisites
 
-    case "$command" in
-    create | "" | -c | --create)
-        create_session "true"
-        ;;
-    attach)
-        attach_session "$SESSION_NAME"
-        ;;
-    detach)
-        detach_session "$SESSION_NAME"
-        ;;
-    destroy)
-        destroy_session "$SESSION_NAME"
-        ;;
-    help | --help | -h)
-        usage
-        ;;
-    *)
-        fail "Unknown option: $command"
-        usage
-        exit 1
-        ;;
-    esac
+  case "$command" in
+  create | "" | -c | --create)
+    create_session "true"
+    ;;
+  attach)
+    attach_session "$SESSION_NAME"
+    ;;
+  detach)
+    detach_session "$SESSION_NAME"
+    ;;
+  destroy)
+    destroy_session "$SESSION_NAME"
+    ;;
+  help | --help | -h)
+    usage
+    ;;
+  *)
+    fail "Unknown option: $command"
+    usage
+    exit 1
+    ;;
+  esac
 }
 
 main "$@"
