minor changes

diff --git a/share/installers/arch b/share/installers/arch
--- a/share/installers/arch
+++ b/share/installers/arch
@@ -1,304 +1,306 @@
 #!/usr/bin/env bash
 
 si() {
-    sudo pacman -S --quiet --noconfirm "$@"
+  sudo pacman -S --quiet --noconfirm "$@"
 
-    # for p in "$@"; do
-    #     slog "Installing package $p"
-    #     sudo pacman -S --needed --quiet --noconfirm "$p"
-    # done
+  # for p in "$@"; do
+  #     slog "Installing package $p"
+  #     sudo pacman -S --needed --quiet --noconfirm "$p"
+  # done
 }
 
 update_packages() {
-    slog "Updating Arch"
+  slog "Updating Arch"
 
-    if ! sudo pacman -Syu --noconfirm --quiet; then
-        die "pacman update/upgrade failed, quitting"
-    fi
+  if ! sudo pacman -Syu --noconfirm --quiet; then
+    die "pacman update/upgrade failed, quitting"
+  fi
 }
 
 aur() {
-    if has_cmd paru; then
-        paru -S --noconfirm "$@"
-    elif has_cmd yay; then
-        yay -S --noconfirm "$@"
-    else
-        die "paru or yay not installed, cannot install $1"
-    fi
+  if has_cmd paru; then
+    paru -S --noconfirm "$@"
+  elif has_cmd yay; then
+    yay -S --noconfirm "$@"
+  else
+    die "paru or yay not installed, cannot install $1"
+  fi
 }
 
 arch_packages() {
-    update_packages
+  update_packages
 
-    slog "Installing packages"
+  slog "Installing packages"
 
-    si git-core github-cli git-delta unzip wget curl trash-cli tar stow \
-        gcc make file starship gum wl-clipboard tree bat eza fzf ripgrep \
-        zoxide fd htop sd yazi bat tealdeer lazygit libsecret net-tools \
-        iproute2 nmap dialog newt python python-pipx python-pip
+  si git-core github-cli git-delta unzip wget curl trash-cli tar stow \
+    gcc make file starship gum wl-clipboard tree bat eza fzf ripgrep \
+    zoxide fd htop sd yazi bat tealdeer lazygit libsecret net-tools \
+    iproute2 nmap dialog newt python python-pipx python-pip
 
-    has_cmd tldr && tldr --update
+  has_cmd tldr && tldr --update
 
-    slog "Installing packages done!"
+  slog "Installing packages done!"
 }
 
 locale_setup() {
-    local LOCALE KEYMAP
-    LOCALE="en_US.UTF-8"
-    KEYMAP="us"
+  local LOCALE KEYMAP
+  LOCALE="en_US.UTF-8"
+  KEYMAP="us"
 
-    slog "Configuring locale and keyboard for Arch Linux..."
+  slog "Configuring locale and keyboard for Arch Linux..."
 
-    sudo sed -i "s/^# *$LOCALE/$LOCALE/" /etc/locale.gen
-    sudo locale-gen
-    echo "LANG=$LOCALE" | sudo tee /etc/locale.conf
+  sudo sed -i "s/^# *$LOCALE/$LOCALE/" /etc/locale.gen
+  sudo locale-gen
+  echo "LANG=$LOCALE" | sudo tee /etc/locale.conf
 
-    echo "KEYMAP=$KEYMAP" | sudo tee /etc/vconsole.conf
-    sudo loadkeys "$KEYMAP"
+  echo "KEYMAP=$KEYMAP" | sudo tee /etc/vconsole.conf
+  sudo loadkeys "$KEYMAP"
 
 }
 
 core_install() {
-    update_packages
+  update_packages
 
-    slog "Installing core packages"
+  slog "Installing core packages"
 
-    si curl wget git trash-cli tree tar unzip stow zstd file
+  si curl wget git trash-cli tree tar unzip stow zstd file
 
-    slog "Core packages installation done!"
+  slog "Core packages installation done!"
 }
 
 system-python_install() {
-    slog "Installing python"
+  slog "Installing python"
 
-    si python python-pipx python-pip python-setuptools python-wheel \
-        python-virtualenv
-    pipx install uv
+  si python python-pipx python-pip python-setuptools python-wheel \
+    python-virtualenv
+  pipx install uv
 
-    slog "Python installation done!"
+  slog "Python installation done!"
 }
 
 paru_install() {
-    has_cmd paru && return 0
-    has_cmd yay && return 0
+  has_cmd paru && return 0
+  has_cmd yay && return 0
 
-    slog "Installing paru"
+  slog "Installing paru"
 
-    frm /tmp/paru
-    git clone https://aur.archlinux.org/paru.git /tmp/paru && cd /tmp/paru && makepkg --syncdeps --noconfirm --install && cd - && frm /tmp/paru
+  frm /tmp/paru
+  git clone https://aur.archlinux.org/paru.git /tmp/paru && cd /tmp/paru && makepkg --syncdeps --noconfirm --install && cd - && frm /tmp/paru
 
-    slog "paru installation done!"
+  slog "paru installation done!"
 }
 
 snap_install() {
-    aur snapd
-    sudo systemctl enable --now snapd
+  aur snapd
+  sudo systemctl enable --now snapd
 }
 
 ui_install() {
-    is_desktop || return 1
+  is_desktop || return 1
 
-    slog "Installing ui"
+  slog "Installing ui"
 
-    si gnome-keyring wl-clipboard flatpak
-    flathub_install
+  si gnome-keyring wl-clipboard flatpak
+  flathub_install
 
-    slog "ui installation done!"
+  slog "ui installation done!"
 }
 
 essential_install() {
-    slog "Installing essential packages"
+  slog "Installing essential packages"
 
-    pkgx_install
+  pkgx_install
 
-    si unarchiver zip tmux pkg-config fuse2 p7zip xz readline micro libnewt \
-        sqlite libffi zlib pkgfile libxcrypt-compat libsecret gawk base-devel
+  si unarchiver zip tmux pkg-config fuse2 p7zip xz readline micro libnewt \
+    sqlite libffi zlib pkgfile libxcrypt-compat libsecret gawk base-devel
 
-    sudo pkgfile --update
-    sudo pacman -Fy
+  sudo pkgfile --update
+  sudo pacman -Fy
 
-    slog "Essential packages installation done!"
+  slog "Essential packages installation done!"
 }
 
 cli-slim_install() {
-    slog "Installing cli tools using pacman"
+  slog "Installing cli tools using pacman"
 
-    si zsh github-cli fzf ripgrep zoxide eza starship
+  si zsh github-cli fzf ripgrep zoxide eza starship
 
-    slog "cli tools installation done!"
+  slog "cli tools installation done!"
 }
 
 cli_install() {
-    slog "Installing cli tools using pacman"
+  slog "Installing cli tools using pacman"
 
-    cli-slim_install
+  cli-slim_install
 
-    si neovim tmux shellcheck shfmt python-pynvim zsh-completions bat jq yq \
-        luarocks duf lazygit ugrep git-delta navi sd gdu hyperfine fd lsd xh \
-        htop nushell bottom plocate tealdeer television dysk yazi pixi procs \
-        dust direnv atuin broot glances curlie superfile choose just dialog \
-        gum lazydocker
+  si neovim tmux shellcheck shfmt python-pynvim zsh-completions bat jq yq \
+    luarocks duf lazygit ugrep git-delta navi sd gdu hyperfine fd lsd xh \
+    htop nushell bottom plocate tealdeer television dysk yazi pixi procs \
+    dust direnv atuin broot glances curlie superfile choose just dialog \
+    gum lazydocker
 
-    has_cmd tldr && tldr --update
+  has_cmd tldr && tldr --update
 
-    system-python_install
+  system-python_install
 
-    slog "cli tools installation done!"
+  slog "cli tools installation done!"
 }
 
 cpp_install() {
-    slog "Installing C++"
+  slog "Installing C++"
 
-    si gcc gdb boost boost-libs catch2 libc++ clang llvm \
-        doxygen graphviz ccache cppcheck pre-commit \
-        valgrind ltrace strace lldb lld cmake
+  si gcc gdb boost boost-libs catch2 libc++ clang llvm \
+    doxygen graphviz ccache cppcheck pre-commit \
+    valgrind ltrace strace lldb lld cmake
 
-    conan_install
+  conan_install
 
-    slog "C++ installation done!"
+  slog "C++ installation done!"
 
-    cmd_check gcc gdb make cmake conan clang clang++ clang-tidy clang-format
+  cmd_check gcc gdb make cmake conan clang clang++ clang-tidy clang-format
 }
 
 vscode_binstall() {
-    slog "Installing vscode"
+  slog "Installing vscode"
 
-    aur visual-studio-code-bin
+  aur visual-studio-code-bin
 
-    slog "vscode installation done!"
+  slog "vscode installation done!"
 
-    cmd_check code
+  cmd_check code
 }
 
 terminal_binstall() {
-    slog "Installing terminal"
+  slog "Installing terminal"
 
-    si ghostty
+  si ghostty
 
-    slog "terminal installation done!"
+  slog "terminal installation done!"
 }
 
 vm-ui_install() {
-    is_desktop || return 1
+  is_desktop || return 1
 
-    slog "Installing virt ui packages"
+  slog "Installing virt ui packages"
 
-    local -a pkgs=("qemu-desktop")
-    has_cmd gnome-boxes || pkgs+=("gnome-boxes")
-    has_cmd virt-install && pkgs+=("virt-manager" "virt-viewer")
+  local -a pkgs=("qemu-desktop")
+  has_cmd gnome-boxes || pkgs+=("gnome-boxes")
+  has_cmd virt-install && pkgs+=("virt-manager" "virt-viewer")
 
-    si "${pkgs[@]}"
+  si "${pkgs[@]}"
 
-    slog "virt ui packages installation done!"
+  slog "virt ui packages installation done!"
 }
 
 cockpit_install() {
-    has_cmd cockpit && return 1
+  has_cmd cockpit && return 1
 
-    slog "Installing cockpit"
+  slog "Installing cockpit"
 
-    si cockpit cockpit-machines cockpit-packagekit cockpit-pcp cockpit-podman \
-        cockpit-storaged
-    sudo systemctl enable --now cockpit.socket
+  si cockpit cockpit-machines cockpit-packagekit cockpit-pcp cockpit-podman \
+    cockpit-storaged
+  sudo systemctl enable --now cockpit.socket
 
-    slog "cockpit installation done!"
+  slog "cockpit installation done!"
 }
 
 vm_install() {
-    slog "Installing vm"
+  slog "Installing vm"
 
-    sudo pacman -R --noconfirm iptables
+  sudo pacman -R --noconfirm iptables
 
-    si iptables-nft libvirt qemu-base virt-install bridge-utils dnsmasq jq \
-        edk2-ovmf virglrenderer libisoburn cloud-utils dmidecode libguestfs \
-        guestfs-tools qemu-hw-display-virtio-gpu libosinfo openbsd-netcat \
-        xmlstarlet osinfo-db ovmf libosinfo openssl
+  si iptables-nft libvirt qemu-base virt-install bridge-utils dnsmasq jq \
+    edk2-ovmf virglrenderer libisoburn cloud-utils dmidecode libguestfs \
+    guestfs-tools qemu-hw-display-virtio-gpu libosinfo openbsd-netcat \
+    xmlstarlet osinfo-db ovmf libosinfo openssl
 
-    slog "vm installation done!"
+  slog "vm installation done!"
 }
 
 docker_install() {
-    has_cmd docker && return 1
+  has_cmd docker && return 1
 
-    slog "Installing docker"
+  slog "Installing docker"
 
-    si docker docker-compose dive slim
+  si docker docker-compose dive slim
 
-    slog "docker installation done!"
+  slog "docker installation done!"
 }
 
 incus_install() {
-    has_cmd incus && return 1
+  has_cmd incus && return 1
 
-    slog "Installing incus"
+  slog "Installing incus"
 
-    si incus qemu-desktop bridge-utils openssl
-    incus_confstall
+  si incus qemu-desktop bridge-utils openssl
+  incus_confstall
 
-    slog "incus installation done!"
+  slog "incus installation done!"
 }
 
 distrobox_install() {
-    has_cmd distrobox && return 1
+  has_cmd distrobox && return 1
 
-    slog "Installing distrobox"
-    si buildah distrobox podman podman-compose
-    slog "distrobox installation done!"
+  slog "Installing distrobox"
+  si buildah distrobox podman podman-compose
+  slog "distrobox installation done!"
 }
 
 desktop_essential_install() {
-    si thunar thunar-archive-plugin wl-clipboard cliphist grim slurp \
-        rofi-wayland waybar dunst nwg-displays nwg-panel xdg-desktop-portal \
-        nwg-bar dolphin swaync ghostty lxappearance qt5ct qt6ct polkit \
-        polkit-kde-agent pavucontrol nm-connection-editor mpv imv nvtop \
-        network-manager-applet otf-font-awesome noto-fonts noto-fonts-emoji \
-        ttf-font-awesome ttf-roboto tumbler firefox kvantum swappy sddm gvfs \
-        papirus-icon-theme bibata-cursor-theme nwg-look reflector
+  si thunar thunar-archive-plugin wl-clipboard cliphist grim slurp \
+    rofi-wayland waybar dunst nwg-displays nwg-panel xdg-desktop-portal \
+    nwg-bar dolphin swaync ghostty lxappearance qt5ct qt6ct polkit \
+    polkit-kde-agent pavucontrol nm-connection-editor mpv imv nvtop \
+    network-manager-applet otf-font-awesome noto-fonts noto-fonts-emoji \
+    ttf-font-awesome ttf-roboto tumbler firefox kvantum swappy sddm gvfs \
+    papirus-icon-theme bibata-cursor-theme nwg-look reflector
 
-    jetbrains-mono_install
-    font-awesome_install
+  jetbrains-mono_install
+  font-awesome_install
 
-    # xorg-server-xwayland
-    # mesa vulkan-intel vulkan-radeon vulkan-mesa-layer
+  # xorg-server-xwayland
+  # mesa vulkan-intel vulkan-radeon vulkan-mesa-layer
 }
 
 hyprland_install() {
-    slog "Installing hyprland packages"
+  slog "Installing hyprland packages"
 
-    desktop_essential_install
-    si hyprcursor hyprgraphics hypridle hyprland hyprland-protocols hyprshot \
-        hyprland-qt-support hyprland-qtutils hyprlock hyprpolkitagent \
-        hyprsunset hyprutils hyprwayland-scanner nwg-dock-hyprland hyprpaper \
-        xdg-desktop-portal-hyprland udisks2 udiskie
+  desktop_essential_install
+  si hyprcursor hyprgraphics hypridle hyprland hyprland-protocols hyprshot \
+    hyprland-qt-support hyprland-qtutils hyprlock hyprpolkitagent \
+    hyprsunset hyprutils hyprwayland-scanner nwg-dock-hyprland hyprpaper \
+    xdg-desktop-portal-hyprland udisks2 udiskie
 
-    slog "hyprland installation done!"
+  slog "hyprland installation done!"
 }
 
 sway_binstall() {
-    slog "Installing sway packages"
+  slog "Installing sway packages"
 
-    desktop_essential_install
-    si sway swaybg swayidle swaylock
+  desktop_essential_install
+  si sway swaybg swayidle swaylock
 
-    slog "sway installation done!"
+  slog "sway installation done!"
 }
 
 firewall_setup() {
-    si nftables firewalld
-    sudo systemctl enable --now firewalld
+  si nftables firewalld
+  sudo systemctl enable --now firewalld
 }
 
 pm_install() {
-    si nmap net-tools iproute2 lm_sensors stress-ng taliscale wireguard-tools \
-        smartmontools memtest86+ glmark2
+  si nmap net-tools iproute2 lm_sensors stress-ng taliscale wireguard-tools \
+    smartmontools memtest86+ glmark2
 }
 
 kde-slim_binstall() {
-    sudo pacman -S --quiet --noconfirm --needed plasma-desktop  noto-fonts \
+  slog "Installing minimal kde plasma..."
+  sudo pacman -S --quiet --noconfirm --needed plasma-desktop noto-fonts \
     pipewire-jack systemsettings kscreen kio-extras udisks2 powerdevil \
     power-profiles-daemon qt6-multimedia-gstreamer
 
-    sudo pacman -S --quiet --noconfirm --needed mesa
+  sudo pacman -S --quiet --noconfirm --needed mesa
+  slog "kde plasma installation done!"
 }
 
 kde_binstall() {
diff --git a/share/installers/tw b/share/installers/tw
--- a/share/installers/tw
+++ b/share/installers/tw
@@ -1,316 +1,318 @@
 #!/usr/bin/env bash
 
 zi() {
-    sudo zypper --non-interactive --quiet install --auto-agree-with-licenses "$@"
+  sudo zypper --non-interactive --quiet install --auto-agree-with-licenses "$@"
 }
 
 si() {
-    zi "$@" && return 0
+  zi "$@" && return 0
 
-    for p in "$@"; do
-        slog "Installing package $p"
-        zi "$p"
-    done
+  for p in "$@"; do
+    slog "Installing package $p"
+    zi "$p"
+  done
 }
 
 update_packages() {
-    slog "Updating SUSE"
+  slog "Updating SUSE"
 
-    if ! { sudo zypper refresh && sudo zypper --non-interactive --quiet dup; }; then
-        die "zypper refresh failed. quitting"
-    fi
+  if ! { sudo zypper refresh && sudo zypper --non-interactive --quiet dup; }; then
+    die "zypper refresh failed. quitting"
+  fi
 }
 
 tw_packages() {
-    update_packages
+  update_packages
 
-    slog "Installing packages"
+  slog "Installing packages"
 
-    si git gh git-delta unzip wget curl trash-cli tar stow gcc make file \
-        starship gum wl-clipboard tree bat eza fzf ripgrep zoxide fd \
-        htop sd tealdeer yazi cheat lazygit libsecret net-tools iproute2 nmap \
-        dialog newt python314 python314-pip python314-pipx osinfo-db-tools
+  si git gh git-delta unzip wget curl trash-cli tar stow gcc make file \
+    starship gum wl-clipboard tree bat eza fzf ripgrep zoxide fd \
+    htop sd tealdeer yazi cheat lazygit libsecret net-tools iproute2 nmap \
+    dialog newt python314 python314-pip python314-pipx osinfo-db-tools
 
-    has_cmd tldr && tldr --update
+  has_cmd tldr && tldr --update
 
-    slog "Installing packages done!"
+  slog "Installing packages done!"
 }
 
 system-python_install() {
-    slog "Installing python"
+  slog "Installing python"
 
-    si python314 python314-virtualenv python314-pip python314-setuptools \
-        python314-pipx
-    pipx install uv
+  si python314 python314-virtualenv python314-pip python314-setuptools \
+    python314-pipx
+  pipx install uv
 
-    slog "Python installation done!"
+  slog "Python installation done!"
 }
 
 locale_setup() {
-    local LOCALE KEYMAP
-    LOCALE="en_US.UTF-8"
-    KEYMAP="us"
+  local LOCALE KEYMAP
+  LOCALE="en_US.UTF-8"
+  KEYMAP="us"
 
-    sudo localectl set-locale LANG="$LOCALE"
+  sudo localectl set-locale LANG="$LOCALE"
 
-    sudo localectl set-keymap "$KEYMAP"
-    sudo localectl set-x11-keymap "$KEYMAP"
+  sudo localectl set-keymap "$KEYMAP"
+  sudo localectl set-x11-keymap "$KEYMAP"
 
-    echo "KEYMAP=$KEYMAP" | sudo tee /etc/vconsole.conf
-    echo "LANG=$LOCALE" | sudo tee /etc/locale.conf
+  echo "KEYMAP=$KEYMAP" | sudo tee /etc/vconsole.conf
+  echo "LANG=$LOCALE" | sudo tee /etc/locale.conf
 
-    sudo loadkeys "$KEYMAP"
+  sudo loadkeys "$KEYMAP"
 }
 
 core_install() {
-    update_packages
+  update_packages
 
-    slog "Installing core packages"
+  slog "Installing core packages"
 
-    si curl wget git tar tree unzip stow file trash-cli which
+  si curl wget git tar tree unzip stow file trash-cli which
 
-    slog "Core packages installation done!"
+  slog "Core packages installation done!"
 }
 
 snap_install() {
-    has_cmd snap && return 0
+  has_cmd snap && return 0
 
-    slog "Installing snap..."
+  slog "Installing snap..."
 
-    sudo zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed snappy
-    sudo zypper --gpg-auto-import-keys refresh
-    sudo zypper dup --from snappy
-    sudo systemctl enable --now snapd
+  sudo zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed snappy
+  sudo zypper --gpg-auto-import-keys refresh
+  sudo zypper dup --from snappy
+  sudo systemctl enable --now snapd
 
-    slog "snap installation done!"
+  slog "snap installation done!"
 }
 
 ui_install() {
-    is_desktop || return 1
+  is_desktop || return 1
 
-    slog "Installing ui"
+  slog "Installing ui"
 
-    si gnome-keyring wl-clipboard flatpak
-    flathub_install
+  si gnome-keyring wl-clipboard flatpak
+  flathub_install
 
-    slog "ui installation done!"
+  slog "ui installation done!"
 }
 
 essential_install() {
-    pkgx_install
-    # snap_install
+  pkgx_install
+  # snap_install
 
-    slog "Installing essential packages"
+  slog "Installing essential packages"
 
-    sudo zypper install -y -t pattern devel_basis
+  sudo zypper install -y -t pattern devel_basis
 
-    si unar zip micro-editor 7zip readline-devel sqlite3-devel libffi-devel \
-        libbz2-devel xz-devel gum libsecret gawk newt
+  si unar zip micro-editor 7zip readline-devel sqlite3-devel libffi-devel \
+    libbz2-devel xz-devel gum libsecret gawk newt
 
-    slog "Essential packages installation done!"
+  slog "Essential packages installation done!"
 }
 
 cli-slim_install() {
-    slog "Installing cli tools using zypper"
+  slog "Installing cli tools using zypper"
 
-    si zsh git starship ripgrep gh fzf zoxide eza
+  si zsh git starship ripgrep gh fzf zoxide eza
 
-    slog "cli tools installation done!"
+  slog "cli tools installation done!"
 }
 
 cli_install() {
-    slog "Installing cli tools using zypper"
+  slog "Installing cli tools using zypper"
 
-    cli-slim_install
+  cli-slim_install
 
-    si neovim sd fd procs lazygit bottom xh plocate tealdeer urlview nushell \
-        lua54-luarocks python3-neovim ImageMagick gdu duf ugrep yazi dysk jq \
-        hyperfine cheat curlie lsd direnv yq tmux htop fd bat git-delta dust \
-        shfmt ShellCheck just dialog atuin broot choose
+  si neovim sd fd procs lazygit bottom xh plocate tealdeer urlview nushell \
+    lua54-luarocks python3-neovim ImageMagick gdu duf ugrep yazi dysk jq \
+    hyperfine cheat curlie lsd direnv yq tmux htop fd bat git-delta dust \
+    shfmt ShellCheck just dialog atuin broot choose
 
-    has_cmd tldr && tldr --update
+  has_cmd tldr && tldr --update
 
-    system-python_install
+  system-python_install
 
-    slog "cli tools installation done!"
+  slog "cli tools installation done!"
 }
 
 cpp_install() {
-    slog "Installing C++"
+  slog "Installing C++"
 
-    si gcc gdb g++ boost-devel catch2-devel ltrace strace lldb lld \
-        clang llvm clang-tools clang-devel valgrind systemtap \
-        doxygen graphviz ccache cppcheck python3-pre-commit cmake
+  si gcc gdb g++ boost-devel catch2-devel ltrace strace lldb lld \
+    clang llvm clang-tools clang-devel valgrind systemtap \
+    doxygen graphviz ccache cppcheck python3-pre-commit cmake
 
-    conan_install
+  conan_install
 
-    slog "C++ installation done!"
+  slog "C++ installation done!"
 }
 
 vscode_binstall() {
-    has_cmd code && return 0
+  has_cmd code && return 0
 
-    slog "Installing vscode"
+  slog "Installing vscode"
 
-    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
-    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/zypp/repos.d/vscode.repo'
-    sudo zypper refresh
-    si code
+  sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
+  sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/zypp/repos.d/vscode.repo'
+  sudo zypper refresh
+  si code
 
-    slog "vscode installation done!"
+  slog "vscode installation done!"
 
-    cmd_check code
+  cmd_check code
 }
 
 terminal_binstall() {
-    has_cmd ghostty && return 1
+  has_cmd ghostty && return 1
 
-    slog "Installing ghostty"
-    si ghostty
-    slog "ghostty installation done!"
+  slog "Installing ghostty"
+  si ghostty
+  slog "ghostty installation done!"
 }
 
 vm-ui_install() {
-    is_desktop || return 1
+  is_desktop || return 1
 
-    slog "Installing virt ui packages"
+  slog "Installing virt ui packages"
 
-    si gnome-boxes
-    has_cmd virt-install && si virt-manager virt-viewer
+  si gnome-boxes
+  has_cmd virt-install && si virt-manager virt-viewer
 
-    slog "virt ui packages installation done!"
+  slog "virt ui packages installation done!"
 }
 
 cockpit_install() {
-    has_cmd cockpit && return 1
+  has_cmd cockpit && return 1
 
-    slog "Installing cockpit"
+  slog "Installing cockpit"
 
-    si systemd-networkd cockpit cockpit-machines cockpit-pcp cockpit-podman \
-        cockpit-storaged cockpit-kdump cockpit-networkmanager \
-        cockpit-packagekit cockpit-system cockpit-tukit
-    # microos_cockpit patterns-microos-cockpit
-    sudo systemctl enable --now cockpit.socket
+  si systemd-networkd cockpit cockpit-machines cockpit-pcp cockpit-podman \
+    cockpit-storaged cockpit-kdump cockpit-networkmanager \
+    cockpit-packagekit cockpit-system cockpit-tukit
+  # microos_cockpit patterns-microos-cockpit
+  sudo systemctl enable --now cockpit.socket
 
-    slog "cockpit installation done!"
+  slog "cockpit installation done!"
 }
 
 vm_install() {
-    slog "Installing libvirt"
+  slog "Installing libvirt"
 
-    si libvirt qemu-kvm virt-install bridge-utils qemu-img qemu-ui-spice-core \
-        qemu-ui-spice-app qemu-char-spice qemu-audio-spice jq xmlstarlet \
-        qemu-hw-display-virtio-gpu qemu-hw-display-virtio-vga qemu-hw-usb-host \
-        qemu-hw-usb-redirect qemu-ovmf-x86_64 qemu-tools qemu-ui-gtk \
-        qemu-ui-opengl libguestfs guestfs-tools libosinfo openssl
+  si libvirt qemu-kvm virt-install bridge-utils qemu-img qemu-ui-spice-core \
+    qemu-ui-spice-app qemu-char-spice qemu-audio-spice jq xmlstarlet \
+    qemu-hw-display-virtio-gpu qemu-hw-display-virtio-vga qemu-hw-usb-host \
+    qemu-hw-usb-redirect qemu-ovmf-x86_64 qemu-tools qemu-ui-gtk \
+    qemu-ui-opengl libguestfs guestfs-tools libosinfo openssl
 
-    slog "libvirt installation done!"
+  slog "libvirt installation done!"
 }
 
 docker_install() {
-    has_cmd docker && return 1
+  has_cmd docker && return 1
 
-    slog "Installing docker"
+  slog "Installing docker"
 
-    si docker docker-compose docker-compose-switch dive slim
+  si docker docker-compose docker-compose-switch dive slim
 
-    slog "docker installation done!"
+  slog "docker installation done!"
 }
 
 incus_install() {
-    has_cmd incus && return 1
+  has_cmd incus && return 1
 
-    slog "Installing incus"
+  slog "Installing incus"
 
-    si incus qemu-kvm qemu-tools bridge-utils openssl
-    incus_confstall
+  si incus qemu-kvm qemu-tools bridge-utils openssl
+  incus_confstall
 
-    slog "incus installation done!"
+  slog "incus installation done!"
 }
 
 distrobox_install() {
-    has_cmd distrobox && return 1
+  has_cmd distrobox && return 1
 
-    slog "Installing distrobox"
-    si buildah distrobox podman podman-remote
-    slog "distrobox installation done!"
+  slog "Installing distrobox"
+  si buildah distrobox podman podman-remote
+  slog "distrobox installation done!"
 }
 
 sway_binstall() {
-    slog "Installing sway"
+  slog "Installing sway"
 
-    sudo zypper install -y -t pattern openSuseway
+  sudo zypper install -y -t pattern openSuseway
 
-    si openSuseway qt6ct alacritty swaylock swaybg swayidle \
-        grim clipman imv mpv bluez slirp qt5ct swaynag waybar \
-        brightnessctl pamixer playerctl greetd mpris-ctl firefox \
-        symbols-only-nerd-fonts jetbrains-mono-fonts wl-clipboard \
-        rofi-wayland SwayNotificationCenter polkit-gnome slurp \
-        SwayNotificationCenter-bash-completion bluemoon tlp \
-        SwayNotificationCenter-zsh-completion qt6ct sway-marker
+  si openSuseway qt6ct alacritty swaylock swaybg swayidle \
+    grim clipman imv mpv bluez slirp qt5ct swaynag waybar \
+    brightnessctl pamixer playerctl greetd mpris-ctl firefox \
+    symbols-only-nerd-fonts jetbrains-mono-fonts wl-clipboard \
+    rofi-wayland SwayNotificationCenter polkit-gnome slurp \
+    SwayNotificationCenter-bash-completion bluemoon tlp \
+    SwayNotificationCenter-zsh-completion qt6ct sway-marker
 
-    jetbrains-mono_install
-    font-awesome_install
+  jetbrains-mono_install
+  font-awesome_install
 
-    cmd_check sway swaylock swaybg swayidle swaymsg sway-marker
-    cmd_check swaynag pactl waybar grim clipman imv mpv
-    cmd_check brightnessctl pamixer playerctl greetd alacritty
-    cmd_check /usr/libexec/polkit-gnome-authentication-agent-1
-    cmd_check bluetoothctl bluemoon tlp firefox slurp qt5ct
-    cmd_check swaync swaync-client
+  cmd_check sway swaylock swaybg swayidle swaymsg sway-marker
+  cmd_check swaynag pactl waybar grim clipman imv mpv
+  cmd_check brightnessctl pamixer playerctl greetd alacritty
+  cmd_check /usr/libexec/polkit-gnome-authentication-agent-1
+  cmd_check bluetoothctl bluemoon tlp firefox slurp qt5ct
+  cmd_check swaync swaync-client
 
-    slog "sway installation done!"
+  slog "sway installation done!"
 }
 
 hyprland_install() {
-    slog "Installing hyprland"
+  slog "Installing hyprland"
 
-    si grep aaa_base bash-completion ghostscript-fonts-std NetworkManager curl \
-        tar pipewire wget xdg-utils sudo xdg-desktop-portal \
-        xdg-desktop-portal-gtk git gzip bzip2 jq adwaita-icon-theme \
-        dejavu-fonts glibc-locale less wl-clipboard google-roboto-fonts \
-        noto-sans-fonts google-droid-fonts google-opensans-fonts \
-        gtk3-metatheme-adwaita noto-coloremoji-fonts noto-emoji-fonts \
-        adobe-sourcecodepro-fonts command-not-found greetd mpris-ctl \
-        metatheme-adwaita-common xdg-desktop-portal-wlr \
-        adobe-sourcesanspro-fonts adobe-sourceserifpro-fonts cantarell-fonts \
-        ghostscript-fonts-other google-carlito-fonts
+  si grep aaa_base bash-completion ghostscript-fonts-std NetworkManager curl \
+    tar pipewire wget xdg-utils sudo xdg-desktop-portal \
+    xdg-desktop-portal-gtk git gzip bzip2 jq adwaita-icon-theme \
+    dejavu-fonts glibc-locale less wl-clipboard google-roboto-fonts \
+    noto-sans-fonts google-droid-fonts google-opensans-fonts \
+    gtk3-metatheme-adwaita noto-coloremoji-fonts noto-emoji-fonts \
+    adobe-sourcecodepro-fonts command-not-found greetd mpris-ctl \
+    metatheme-adwaita-common xdg-desktop-portal-wlr \
+    adobe-sourcesanspro-fonts adobe-sourceserifpro-fonts cantarell-fonts \
+    ghostscript-fonts-other google-carlito-fonts
 
-    si hyprcursor hypridle hyprland hyprland-bash-completion hyprland-devel \
-        hyprlock hyprland-wallpapers hyprland-zsh-completion hyprpaper \
-        hyprpicker hyprpolkitagent hyprshot xdg-desktop-portal-hyprland \
-        hyprland-qt-support hyprland-qtutils qt6ctwaybar imv mpv \
-        clipman bluez slirp qt5ct qt6ct ghostty firefox \
-        brightnessctl pamixer playerctl greetd bluemoon tlp slurp mpris-ctl \
-        symbols-only-nerd-fonts jetbrains-mono-fonts wl-clipboard rofi-wayland \
-        SwayNotificationCenter SwayNotificationCenter-bash-completion \
-        SwayNotificationCenter-zsh-completion
+  si hyprcursor hypridle hyprland hyprland-bash-completion hyprland-devel \
+    hyprlock hyprland-wallpapers hyprland-zsh-completion hyprpaper \
+    hyprpicker hyprpolkitagent hyprshot xdg-desktop-portal-hyprland \
+    hyprland-qt-support hyprland-qtutils qt6ctwaybar imv mpv \
+    clipman bluez slirp qt5ct qt6ct ghostty firefox \
+    brightnessctl pamixer playerctl greetd bluemoon tlp slurp mpris-ctl \
+    symbols-only-nerd-fonts jetbrains-mono-fonts wl-clipboard rofi-wayland \
+    SwayNotificationCenter SwayNotificationCenter-bash-completion \
+    SwayNotificationCenter-zsh-completion
 
-    jetbrains-mono_install
+  jetbrains-mono_install
 
-    cmd_check hyprcursor hypridle hyprctl hyprlock hyproiccker
-    cmd_check pactl waybar clipman imv mpv hyprshot ghostty
-    cmd_check brightnessctl pamixer playerctl greetd
-    # cmd_check /usr/libexec/polkit-gnome-authentication-agent-1
-    cmd_check bluetoothctl bluemoon tlp firefox slurp qt5ct
-    cmd_check swaync swaync-client
+  cmd_check hyprcursor hypridle hyprctl hyprlock hyproiccker
+  cmd_check pactl waybar clipman imv mpv hyprshot ghostty
+  cmd_check brightnessctl pamixer playerctl greetd
+  # cmd_check /usr/libexec/polkit-gnome-authentication-agent-1
+  cmd_check bluetoothctl bluemoon tlp firefox slurp qt5ct
+  cmd_check swaync swaync-client
 
-    slog "hyprland installation done!"
+  slog "hyprland installation done!"
 }
 
 pm_install() {
-    si net-tools iproute2 nmap lm_sensors stress-ng taliscale wireguard-tools \
-        smartmontools memtest86+ glmark2
+  si net-tools iproute2 nmap lm_sensors stress-ng taliscale wireguard-tools \
+    smartmontools memtest86+ glmark2
 }
 
 kde-slim_binstall() {
-    sudo zypper install -y --no-recommends plasma6-desktop systemsettings6 \
+  slog "Installing minimal kde plasma..."
+  sudo zypper install -y --no-recommends plasma6-desktop systemsettings6 \
     kscreen6 kio-extras udisks2 powerdevil6 power-profiles-daemon
+  slog "kde plasma installation done!"
 }
 
 kde_binstall() {
   kde-slim_binstall
 
-  sudo zypper install -y --no-recommends  discover6 discover6-backend-flatpak \
+  sudo zypper install -y --no-recommends discover6 discover6-backend-flatpak \
     discover6-backend-packagekit
 }
