minor changes

diff --git a/share/installers/atomic b/share/installers/atomic
--- a/share/installers/atomic
+++ b/share/installers/atomic
@@ -614,24 +614,24 @@ libvirt_confstall() {
 
     add_user_to_groups "$(whoami)" libvirt libvirtd kvm libvirt-qemu
 
-    # local libvirt_group
-    # if group_exists libvirtd; then
-    #     libvirt_group=libvirtd
-    # else
-    #     libvirt_group=libvirt
-    # fi
+    local libvirt_group
+    if group_exists libvirtd; then
+        libvirt_group=libvirtd
+    else
+        libvirt_group=libvirt
+    fi
 
-    # sg "$libvirt_group" -c '
-    # if ! virsh net-list --all | grep -q default; then
-    #     virsh net-define /usr/share/libvirt/networks/default.xml
-    #     virsh net-start default
-    #     virsh net-autostart default
-    # fi
+    sg "$libvirt_group" -c '
+    if ! virsh --connect qemu:///system net-list --all | grep -q default; then
+        # virsh net-define /usr/share/libvirt/networks/default.xml
+        virsh --connect qemu:///system net-start default
+        virsh --connect qemu:///system net-autostart default
+    fi
 
-    # if ! virsh net-list --all | grep -q default; then
-    #     echo "Failed to create default network" >&2
-    # fi
-    # '
+    if ! virsh --connect qemu:///system net-list --all | grep -q default; then
+        echo "Failed to create default network" >&2
+    fi
+    '
 }
 
 atomic_nvim_install() {
