minor fixes

diff --git a/share/installers/atomic b/share/installers/atomic
--- a/share/installers/atomic
+++ b/share/installers/atomic
@@ -552,16 +552,17 @@ libvirt_config_install() {
 
     sudo usermod -aG libvirt "$(whoami)"
 
-    newgrp libvirt <<EOF
+    sg libvirt -c '
     if ! virsh net-list --all | grep -q default; then
-         virsh net-define /usr/share/libvirt/networks/default.xml
-         virsh net-start default
-         virsh net-autostart default
+        virsh net-define /usr/share/libvirt/networks/default.xml
+        virsh net-start default
+        virsh net-autostart default
     fi
+
     if ! virsh net-list --all | grep -q default; then
-         warn "Failed to create default network"
+        echo "Failed to create default network" >&2
     fi
-EOF
+    '
 }
 
 atomic_nvim_install() {
