minor fixes

diff --git a/share/installers/atomic b/share/installers/atomic
--- a/share/installers/atomic
+++ b/share/installers/atomic
@@ -244,102 +244,101 @@ nosudo_groupstall() {
     atomic_distrobox_install
 }
 
-
 gnome_extensions_install() {
-  if ! has_cmd gext; then
-    if ! has_cmd pipx; then
-      warn "pipx not installed, skipping gnome extensions"
-      return 1
+    if ! has_cmd gext; then
+        if ! has_cmd pipx; then
+            warn "pipx not installed, skipping gnome extensions"
+            return 1
+        fi
+
+        pipx install gnome-extensions-cli --system-site-packages
+        cmd_check gext
     fi
 
-    pipx install gnome-extensions-cli --system-site-packages
-    cmd_check gext
-  fi
+    slog "Installing gnome extensions"
 
-  slog "Installing gnome extensions"
+    gext install windowsNavigator@gnome-shell-extensions.gcampax.github.com
+    gext install Vitals@CoreCoding.com
+    gext install tailscale@joaophi.github.com
+    gext install tilingshell@ferrarodomenico.com
+    gext install CoverflowAltTab@palatis.blogspot.com
+    gext install just-perfection-desktop@just-perfection
+    gext install blur-my-shell@aunetx
+    gext install undecorate@sun.wxg@gmail.com
+    gext install AlphabeticalAppGrid@stuarthayhurst
 
-  gext install windowsNavigator@gnome-shell-extensions.gcampax.github.com
-  gext install Vitals@CoreCoding.com
-  gext install tailscale@joaophi.github.com
-  gext install tilingshell@ferrarodomenico.com
-  gext install CoverflowAltTab@palatis.blogspot.com
-  gext install just-perfection-desktop@just-perfection
-  gext install blur-my-shell@aunetx
-  gext install undecorate@sun.wxg@gmail.com
-  gext install AlphabeticalAppGrid@stuarthayhurst
-
-  slog "gnome extensions installation done!"
+    slog "gnome extensions installation done!"
 }
 
 gnome_settings_install() {
 
-  if ! has_cmd gsettings; then
-    warn "gsettings not found, skipping gnome basic settings"
-    return 1
-  fi
+    if ! has_cmd gsettings; then
+        warn "gsettings not found, skipping gnome basic settings"
+        return 1
+    fi
 
-  slog "gnome settings"
+    slog "gnome settings"
 
-  gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"
-  gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
-  gsettings set org.gnome.desktop.interface icon-theme 'Adwaita-dark'
-  gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
-  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
-  gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
-  gsettings set org.gnome.desktop.interface accent-color 'purple'
+    gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"
+    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
+    gsettings set org.gnome.desktop.interface icon-theme 'Adwaita-dark'
+    gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
+    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
+    gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
+    gsettings set org.gnome.desktop.interface accent-color 'purple'
 
-  # Use 4 fixed workspaces instead of dynamic mode
-  gsettings set org.gnome.mutter dynamic-workspaces false
-  gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
+    # Use 4 fixed workspaces instead of dynamic mode
+    gsettings set org.gnome.mutter dynamic-workspaces false
+    gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
 
-  # Center new windows in the middle of the screen
-  gsettings set org.gnome.mutter center-new-windows true
+    # Center new windows in the middle of the screen
+    gsettings set org.gnome.mutter center-new-windows true
 
-  # Set JetBrains Mono as the default monospace font
-  gsettings set org.gnome.desktop.interface monospace-font-name 'JetbrainsMono Nerd Font 11'
+    # Set JetBrains Mono as the default monospace font
+    gsettings set org.gnome.desktop.interface monospace-font-name 'JetbrainsMono Nerd Font 11'
 
-  slog "gnome settings done!"
+    slog "gnome settings done!"
 }
 
 gnome_flatpaks_install() {
-  fpi page.tesk.Refine
-  fpi com.github.tchx84.Flatseal
-  fpi io.github.flattool.Ignition
-  fpi io.github.flattool.Warehouse
-  fpi io.missioncenter.MissionCenter
-  fpi org.gnome.World.PikaBackup
-  fpi org.gnome.Papers
-  fpi org.gnome.Boxes
+    fpi page.tesk.Refine
+    fpi com.github.tchx84.Flatseal
+    fpi io.github.flattool.Ignition
+    fpi io.github.flattool.Warehouse
+    fpi io.missioncenter.MissionCenter
+    fpi org.gnome.World.PikaBackup
+    fpi org.gnome.Papers
+    fpi org.gnome.Boxes
 }
 
 # https://github.com/basecamp/omakub/blob/master/install/desktop/set-gnome-extensions.sh
 gnome_config_install() {
-  if ! is_gnome; then
-    warn "Not running GNOME, skipping GNOME config"
-    return 1
-  fi
+    if ! is_gnome; then
+        warn "Not running GNOME, skipping GNOME config"
+        return 1
+    fi
 
-  slog "gnome config"
+    slog "gnome config"
 
-  if is_ubuntu; then
-    has_cmd si && si gnome-shell-extension-manager gnome-tweak-tool gnome-sushi gnome-software-plugin-flatpak
-  elif is_fedora && ! is_atomic; then
-    has_cmd si && si gnome-extensions-app gnome-tweaks
-  fi
+    if is_ubuntu; then
+        has_cmd si && si gnome-shell-extension-manager gnome-tweak-tool gnome-sushi gnome-software-plugin-flatpak
+    elif is_fedora && ! is_atomic; then
+        has_cmd si && si gnome-extensions-app gnome-tweaks
+    fi
 
-  if is_ubuntu; then
-    gnome-extensions disable tiling-assistant@ubuntu.com
-    gnome-extensions disable ubuntu-appindicators@ubuntu.com
-    gnome-extensions disable ubuntu-dock@ubuntu.com
-    gnome-extensions disable ding@rastersoft.com
-  fi
+    if is_ubuntu; then
+        gnome-extensions disable tiling-assistant@ubuntu.com
+        gnome-extensions disable ubuntu-appindicators@ubuntu.com
+        gnome-extensions disable ubuntu-dock@ubuntu.com
+        gnome-extensions disable ding@rastersoft.com
+    fi
 
-  gnome_settings_install
-  #   gnome_keybindings_install
-  gnome_flatpaks_install
-  gnome_extensions_install
+    gnome_settings_install
+    #   gnome_keybindings_install
+    gnome_flatpaks_install
+    gnome_extensions_install
 
-  slog "gnome config done!"
+    slog "gnome config done!"
 }
 
 fedora-atomic_groupstall() {
@@ -724,7 +723,7 @@ tbox_default() {
     has_cmd toolbox || return
 
     toolbox --assumeyes create
-    toolbox run bash -c "$(curl -sSL https://dub.sh/aPKPT8V)" -- box-default
+    toolbox run bash -ic "$(curl -sSL https://dub.sh/aPKPT8V)" -- box-default
 }
 
 dbox_default() {
@@ -732,7 +731,7 @@ dbox_default() {
 
     slog "Creating default distrobox"
     distrobox create --yes
-    distrobox enter -- bash -c "$(curl -sSL https://dub.sh/aPKPT8V)" -- box-default
+    distrobox enter -- bash -ic "$(curl -sSL https://dub.sh/aPKPT8V)" -- box-default
     slog "Default distrobox created!"
 }
 
@@ -752,6 +751,6 @@ dbox_with_home() {
     distrobox list | grep -q "^${osname}$" && return
 
     "dbox_$os" $osname
-    distrobox enter "${osname}" -- bash -c "$(curl -sSL https://dub.sh/aPKPT8V)" -- box-default
+    distrobox enter "${osname}" -- bash -ic "$(curl -sSL https://dub.sh/aPKPT8V)" -- box-default
     slog "distrobox ${osname} created!"
 }
