minor changes

diff --git a/share/fns b/share/fns
--- a/share/fns
+++ b/share/fns
@@ -1,13 +1,23 @@
 #!/usr/bin/env bash
 
 # shellcheck disable=SC2120
+# shellcheck disable=SC1091
 
 font-names() {
-  has_cmd fc-list || err_exit "fc-list not available"
+  if ! has_cmd fc-list; then
+    warn "fc-list not installed, cannot list fonts"
+    return 1
+  fi
+
   fc-list : family | cut -d: -f2 | sed 's/^ //g' | sort | uniq
 }
 
 git-checkout-previous-file() {
+  if ! has_cmd git; then
+    warn "git not installed, cannot checkout previous file version"
+    return 1
+  fi
+
   if [ -z "$1" ]; then
     echo "Usage: git-checkout-previous-file <file>"
     return 1
@@ -23,132 +33,12 @@ git-checkout-previous-file() {
 }
 
 osquery-update-db() {
+  if ! has_cmd osqueryi; then
+    warn "osqueryi not installed, cannot update osquery database"
+    return 1
+  fi
+
   sudo osinfo-db-import --system --latest
-}
-
-tbox-alpine() {
-  local CONTAINER_NAME=${1:-alpine}
-  slog "Creating distrobox $CONTAINER_NAME"
-
-  if toolbox create \
-    --assumeyes \
-    --image quay.io/toolbx-images/alpine-toolbox:latest \
-    "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating distrobox $CONTAINER_NAME"
-  fi
-}
-
-tbox-arch() {
-  local CONTAINER_NAME=${1:-arch}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create --assumeyes --distro arch "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-fedora() {
-  local CONTAINER_NAME=${1:-fedora}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create --assumeyes --distro fedora "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-ubuntu() {
-  local CONTAINER_NAME=${1:-ubuntu}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create --assumeyes --distro ubuntu --release 24.10 "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-tw() {
-  local CONTAINER_NAME=${1:-tw}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create \
-    --assumeyes \
-    --image quay.io/toolbx-images/opensuse-toolbox:tumbleweed \
-    "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-rocky() {
-  local CONTAINER_NAME=${1:-rocky}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create \
-    --assumeyes \
-    --image quay.io/rockylinux/rockylinux:9 \
-    "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-centos() {
-  local CONTAINER_NAME=${1:-centos}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create \
-    --assumeyes \
-    --image quay.io/toolbx-images/centos-toolbox:latest \
-    "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-debian() {
-  local CONTAINER_NAME=${1:-debian}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create \
-    --assumeyes \
-    --image quay.io/toolbx-images/debian-toolbox:latest \
-    "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-rhel() {
-  local CONTAINER_NAME=${1:-rhel}
-  slog "Creating toolbox $CONTAINER_NAME"
-
-  if toolbox create \
-    --assumeyes \
-    --image registry.access.redhat.com/ubi9/ubi-toolbox:latest \
-    "$CONTAINER_NAME"; then
-    toolbox enter "$CONTAINER_NAME"
-    slog "Done creating toolbox $CONTAINER_NAME"
-  fi
-}
-
-tbox-create-all() {
-  slog "Creating toolbox containers"
-
-  is_arch || toolbox create --assumeyes --distro arch arch
-  is_fedora || toolbox create --assumeyes --distro fedora fedora
-  is_ubuntu || toolbox create --assumeyes --distro ubuntu --release 24.10 ubuntu
-  # toolbox create --distro rhel --release 9.5 rhel
-
-  is_tw || toolbox create --assumeyes --image quay.io/toolbx-images/opensuse-toolbox:tumbleweed tw
-  is_rocky || toolbox create --assumeyes --image quay.io/rockylinux/rockylinux:9 rocky
-  # is_centos || toolbox create --image quay.io/toolbx-images/centos-toolbox:latest centos
-
-  toolbox create
-
-  slog "Done creating toolbox containers"
 }
 
 function safe_push() {
@@ -167,123 +57,6 @@ one-shell-tmux() {
   fi
 
   exec tmux attach-session -t "$tmux_session"
-}
-
-incus-ubuntu-lxc() {
-  incus launch images:ubuntu/24.04 ubuntu # --config limits.cpu=1 --config limits.memory=192MiB
-}
-
-incus-fedora-lxc() {
-  incus launch images:fedora/42 fedora
-}
-
-incus-tw-lxc() {
-  incus launch images:opensuse/tumbleweed tw
-}
-
-incus-arch-lxc() {
-  incus launch images:archlinux/current archlinux
-}
-
-incus-containers() {
-  slog "Creating incus containers"
-
-  incus-ubuntu-lxc
-  incus-fedora-lxc
-  incus-tw-lxc
-  incus-arch-lxc
-
-  slog "Creating incus containers done!"
-}
-
-incus-ubuntu-vm() {
-  incus launch images:ubuntu/24.04 ubuntu-vm --vm
-}
-
-incus-fedora-vm() {
-  incus launch images:fedora/42 fedora-vm --vm
-}
-
-incus-tw-vm() {
-  incus launch images:opensuse/tumbleweed-vm tw --vm
-}
-
-incus-arch-vm() {
-  incus launch images:archlinux/current archlinux-vm --vm
-}
-
-incus-nixos() {
-  incus launch images:nixos/unstable --vm nixos-vm -c security.secureboot=false
-}
-
-ivms() {
-  slog "Creating incus vms"
-
-  incus-ubuntu-vm
-  incus-fedora-vm
-  incus-tw-vm
-  incus-arch-vm
-
-  slog "Creating incus vms done!"
-}
-
-virt-docker() {
-  local VM_NAME=${1:-docker}
-  slog "Creating Docker VM: $VM_NAME"
-  sleep 1
-  vm-create --distro debian --name "$VM_NAME" --docker
-}
-
-virt-incus() {
-  local VM_NAME=${1:-incus}
-  slog "Creating Incus VM: $VM_NAME"
-  sleep 1
-  vm-create --distro debian --name "$VM_NAME" --dotfiles incus
-}
-
-virt-nix() {
-  local VM_NAME=${1:-nix}
-  slog "Creating Debian VM: $VM_NAME"
-  sleep 1
-  vm-create --distro debian --name "$VM_NAME" --nix
-}
-
-virt-dev() {
-  local VM_NAME=${1:-dev}
-  slog "Creating Dev VM: $VM_NAME"
-  sleep 1
-  vm-create --distro debian --name "$VM_NAME" --docker --brew
-}
-
-virt-ilm() {
-  local VM_NAME=${1:-ilm}
-  slog "Creating ilm VM: $VM_NAME"
-  sleep 1
-  vm-create --distro debian --name "$VM_NAME" --dotfiles min
-}
-
-virt-exec() {
-  if [[ $# -ne 3 ]]; then
-    fail "Usage: virt-exec <vm-name> <group>"
-    return 1
-  fi
-
-  local username="$1"
-  local vm_name="$2"
-  local extra_arg="$3"
-
-  # shellcheck disable=SC2029
-  ssh "$username@$vm_name" "bash -c \"\$(curl -sSL ${ILM_SETUP_URL})\" -- $extra_arg"
-
-  #     virsh qemu-agent-command "$vm_name" \
-  #         "$(jq -nc --arg cmd "bash -c $cmd" '{
-  #     execute: "guest-exec",
-  #     arguments: {
-  #       path: "/usr/bin/env",
-  #       arg: ["bash","-c",$cmd],
-  #       "capture-output": true
-  #     }
-  #   }')"
 }
 
 nvim-update() {
@@ -390,16 +163,7 @@ syslogs() {
   sudo journalctl -b -p 3 -xn
 }
 
-# shellcheck disable=SC2120
-tbox-group() {
-  has_cmd toolbox || return 0
-
-  toolbox --assumeyes create
-
-  local group=${1:-shell}
-  toolbox run bash -c "$(curl -sSL "${ILM_SETUP_URL}")" -- "$group"
-}
-
-tbox-dev() {
-  tbox-group dbox-dev-atomic
-}
+source "${DOT_DIR}/share/dbox-fns"
+source "${DOT_DIR}/share/tbox-fns"
+source "${DOT_DIR}/share/incus-fns"
+source "${DOT_DIR}/share/virt-fns"
diff --git a/share/utils b/share/utils
--- a/share/utils
+++ b/share/utils
@@ -1033,16 +1033,24 @@ file_check() {
 }
 
 hms() {
+  if ! has_cmd nix; then
+    fail "nix not installed, cannot run hms"
+    return 1
+  fi
+
+  local profile=${1:-"${USER}"}
   local hms_dir
+
   if dir_exists "$DOT_DIR/extras/home-manager"; then
     hms_dir="$DOT_DIR/extras/home-manager"
   elif dir_exists ~/home-manager-config; then
     hms_dir=~/home-manager-config
   else
-    err_exit "home-manager-config not found, cannot run hms"
+    fail "home-manager-config not found, cannot run hms"
+    return 1
   fi
 
-  nix run home-manager -- switch --flake "$hms_dir"#"${USER}" --impure -b bak
+  nix run home-manager -- switch --flake "$hms_dir"#"${profile}" --impure -b bak
 }
 
 SUDO_KEEPALIVE_PID=""
@@ -1088,7 +1096,8 @@ download_to() {
   elif has_cmd wget; then
     wget -nv "$1" -O "$2"
   else
-    err_exit "curl or wget must be installed"
+    fail "curl or wget must be installed"
+    return 1
   fi
 }
 
@@ -1480,7 +1489,6 @@ source_installers() {
     source_curl "$INSTALLERS/box" # some box fns are usefule in atomic too!
     source_curl "$INSTALLERS/atomic"
     # source_curl "$SHARE/fns"
-    # source_curl "$SHARE/dbox-fns"
   fi
 }
 
