refactoring

diff --git a/installers/apt/debian b/installers/apt/debian
--- a/installers/apt/debian
+++ b/installers/apt/debian
@@ -2,7 +2,13 @@
 
 {
 
-sudo apt-get install -y curl sudo
+if command -v apt-get > /dev/null; then
+    sudo apt-get install -y curl sudo
+else
+    echo "apt-get not found. Please install apt-get and try again."
+    exit 1
+fi
+
 source <(curl -sSL https://dub.sh/z3pTnAK)
 
 main() {
@@ -26,6 +32,6 @@ main() {
 
 is_debian || err_exit "This installer works only on Debian. Quitting."
 
-bootstrap "Debian development system"
+bootstrap "Debian development system(vm)"
 
 }
diff --git a/installers/apt/min b/installers/apt/min
--- a/installers/apt/min
+++ b/installers/apt/min
@@ -2,7 +2,13 @@
 
 {
 
-sudo apt-get install -y curl sudo
+if command -v apt-get > /dev/null; then
+    sudo apt-get install -y curl sudo
+else
+    echo "apt-get not found. Please install apt-get and try again."
+    exit 1
+fi
+
 source <(curl -sSL https://dub.sh/z3pTnAK)
 
 main() {
@@ -18,6 +24,6 @@ is_apt || err_exit "This installer works only on Ubuntu or Debian. Quitting."
 
 export DEBIAN_FRONTEND=noninteractive
 
-bootstrap "Ubuntu/Debian setup"
+bootstrap "Ubuntu/Debian setup(min)"
 
 }
diff --git a/installers/apt/ubuntu b/installers/apt/ubuntu
--- a/installers/apt/ubuntu
+++ b/installers/apt/ubuntu
@@ -3,7 +3,13 @@
 
 {
 
-sudo apt-get install -y curl
+if command -v apt-get > /dev/null; then
+    sudo apt-get install -y curl
+else
+    echo "apt-get not found. Please install apt-get and try again."
+    exit 1
+fi
+
 source <(curl -sSL https://dub.sh/z3pTnAK)
 
 flatpak_apps_install() {
@@ -62,6 +68,6 @@ main() {
 
 is_apt || err_exit "This script works only on Ubuntu. Quitting."
 
-bootstrap "Ubuntu desktop setup"
+bootstrap "Ubuntu desktop setup(desktop)"
 
 }
