improve autotiling installation

diff --git a/share/dot-local/share/ilm/installers/common b/share/dot-local/share/ilm/installers/common
--- a/share/dot-local/share/ilm/installers/common
+++ b/share/dot-local/share/ilm/installers/common
@@ -1279,10 +1279,15 @@ gnome_settings() {
 }
 
 sway_config_install() {
-    python3 -m ensurepip --upgrade
-    python3 -m pip install --upgrade pip
-    python3 -m pip install i3ipc
-    python3 -m pip install autotiling
+    has_cmd pip || has_cmd python3 && python3 -m ensurepip --user --default-pip
+
+    if ! has_cmd pip; then
+        warn "pip not installed, cannot install autotiling"
+        return 1
+    fi
+
+    pip install --user --force-reinstall --upgrade i3ipc
+    pip install --user --force-reinstall --upgrade autotiling
 }
 
 }
